### ISSUE TITLE
匿名模式下写入数据权限已经打开了，可还是无法向手机里复制文件

### ISSUE THREAD

**Issue by hualuoshuijia** [ghmxr/ftpshare#2]
匿名模式下写入数据权限已经打开了，可还是无法向手机里复制写入文件，读出可以。但登陆模式正常写入读出

手机坚果pro2 安卓7.1.1

![image](https://user-images.githubusercontent.com/49584289/91633536-8e431900-ea1b-11ea-8d22-7efd0878694e.png)

**Comment by ghmxr** [comment]
请提供拷贝时的报错截图，如果报错码为501可以试试将文件名重命名为纯英文或数字再试一试。

**Comment by hualuoshuijia** [comment]
> 请提供拷贝时的报错截图,如果报错码为501可以试试将文件名重命名为纯英文或数字再试一试。

文件名不能有汉字，纯英文的倒是可以
![image](https://user-images.githubusercontent.com/49584289/91791916-eb6ee280-ec46-11ea-9653-906e5c60b48d.png)

**Comment by ghmxr** [comment]
> > 请提供拷贝时的报错截图,如果报错码为501可以试试将文件名重命名为纯英文或数字再试一试。
> 
> 文件名不能有汉字，纯英文的倒是可以
> ![image](https://user-images.githubusercontent.com/49584289/91791916-eb6ee280-ec46-11ea-9653-906e5c60b48d.png)

试试将编码调整为GBK，如果仍然有问题就像这样更改文件名为纯英文数字就可以了，后续如有机会将再优化更新。

**Comment by hualuoshuijia** [comment]
> > > 请提供拷贝时的报错截图,如果报错码为501可以试试将文件名重命名为纯英文或数字再试一试。
> > 
> > 
> > 文件名不能有汉字，纯英文的倒是可以
> > ![image](https://user-images.githubusercontent.com/49584289/91791916-eb6ee280-ec46-11ea-9653-906e5c60b48d.png)
> 
> 试试将编码调整为GBK，如果仍然有问题就像这样更改文件名为纯英文数字就可以了，后续如有机会将再优化更新。

好了  ，谢谢 ， 多谢你们这些不辞辛劳的，与人方便的程序员们，
